  sudo: required

  language: generic

  services:
    - docker

  before_install:
    - echo "start createing an image with dockerfile"
    - docker build -t react_app-react -f Dockerfile.dev .

  script:
    - docker run -e CI=true react_app-react npm run test -- --coverage

  after_success:
    - echo "Test Success"